In [0]:
!wget https://github.com/wshuyi/info-5731-public/raw/master/yelp-polarity-middle-size.pickle

--2019-03-05 22:02:51--  https://github.com/wshuyi/info-5731-public/raw/master/yelp-polarity-middle-size.pickle
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/wshuyi/info-5731-public/master/yelp-polarity-middle-size.pickle [following]
--2019-03-05 22:02:51--  https://raw.githubusercontent.com/wshuyi/info-5731-public/master/yelp-polarity-middle-size.pickle
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16174268 (15M) [application/octet-stream]
Saving to: ‘yelp-polarity-middle-size.pickle’

yelp-polarity-middl 100%[===================>]  15.42M  50.3MB/s    in 0.3s    

2019-03-05

In [0]:
import pickle

In [0]:
with open("yelp-polarity-middle-size.pickle", 'rb') as f:
  train, valid, test = pickle.load(f)

In [0]:
train.shape

(16000, 2)

In [0]:
train.head()

sentiment                                               text
0          0  If you're leaving Vegas, know that this is the...
1          1  We were hungry and so quick bites of pizzas sa...
2          0  I have been calling around to various bakeries...
3          0  The first few visits here, we enjoyed it. The ...
4          0  Horrible service, menus never provided. Had to...

In [0]:
len(train[train.sentiment == 1])

8000

In [0]:
valid.shape

(4000, 2)

In [0]:
from sklearn.feature_extraction.text import CountVectorizer

In [0]:
vect = CountVectorizer()
vect.fit_transform(train.text)

<16000x40027 sparse matrix of type '<class 'numpy.int64'>'
	with 1319669 stored elements in Compressed Sparse Row format>

In [0]:
matrix = vect.fit_transform(train.text).toarray()

In [0]:
matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 0, 0, 0]], dtype=int64)

In [0]:
matrix.shape

(16000, 40027)

In [0]:
vect.get_feature_names()

['00',
 '000',
 '007',
 '00am',
 '00p',
 '00pm',
 '00pp',
 '01',
 '02',
 '03',
 '04',
 '0404',
 '0477',
 '05',
 '0500',
 '0505',
 '0540',
 '05pm',
 '06',
 '06am',
 '06pm',
 '07',
 '0730',
 '0792',
 '08',
 '0830',
 '09',
 '0_o',
 '0cbuqygq',
 '0f',
 '0p',
 '0star',
 '0ur',
 '10',
 '100',
 '1000',
 '10000',
 '1007',
 '100f',
 '100g',
 '100ish',
 '100k',
 '100mbps',
 '100x',
 '101',
 '1015am',
 '1015pm',
 '102',
 '103',
 '1030',
 '1030am',
 '104',
 '10419',
 '1045',
 '105',
 '106',
 '107',
 '108',
 '109',
 '1092',
 '10a',
 '10am',
 '10bucks',
 '10h',
 '10ish',
 '10k',
 '10min',
 '10mins',
 '10oz',
 '10p',
 '10pm',
 '10pp',
 '10th',
 '10x',
 '10yrs',
 '11',
 '110',
 '1100',
 '1100th',
 '111',
 '1110',
 '111shiftone',
 '112',
 '1130',
 '1130am',
 '1140',
 '1145am',
 '115',
 '1150',
 '116',
 '117',
 '118',
 '119',
 '11am',
 '11ish',
 '11oz',
 '11p',
 '11pm',
 '11th',
 '11x13',
 '12',
 '120',
 '1200',
 '1204',
 '122',
 '1230am',
 '1230pm',
 '125',
 '1250am',
 '127',
 '128449',
 '129',
 '12am'

customize


In [0]:
vect = CountVectorizer(stop_words='english', token_pattern =u'(?u)\\b[^\\d\\W]\\w+\\b', max_df=0.8, min_df=2, max_features=2000)
vect.fit_transform(train.text)

<16000x2000 sparse matrix of type '<class 'numpy.int64'>'
	with 596026 stored elements in Compressed Sparse Row format>

In [0]:
matrix = vect.fit_transform(train.text).toarray()

In [0]:
matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [0]:
matrix.shape

(16000, 2000)

In [0]:
vect.get_feature_names()

['able',
 'absolute',
 'absolutely',
 'access',
 'accommodating',
 'account',
 'act',
 'acted',
 'actual',
 'actually',
 'add',
 'added',
 'addition',
 'additional',
 'address',
 'admit',
 'adult',
 'advantage',
 'advice',
 'affordable',
 'afternoon',
 'age',
 'ago',
 'agree',
 'agreed',
 'ahead',
 'air',
 'airport',
 'alcohol',
 'allow',
 'allowed',
 'alot',
 'alright',
 'amazing',
 'ambiance',
 'ambience',
 'american',
 'annoyed',
 'annoying',
 'answer',
 'answered',
 'anymore',
 'anytime',
 'anyways',
 'apart',
 'apartment',
 'apologize',
 'apologized',
 'apology',
 'apparently',
 'appeared',
 'appetizer',
 'appetizers',
 'apple',
 'appointment',
 'appreciate',
 'appreciated',
 'apps',
 'area',
 'areas',
 'aren',
 'aria',
 'arizona',
 'arrive',
 'arrived',
 'art',
 'asada',
 'asian',
 'aside',
 'ask',
 'asked',
 'asking',
 'asparagus',
 'ass',
 'assume',
 'ate',
 'atmosphere',
 'attempt',
 'attention',
 'attentive',
 'attitude',
 'au',
 'authentic',
 'available',
 'average',
 'avoca

In [0]:
headers = vect.get_feature_names()

In [0]:
import pandas as pd

In [0]:
term_matrix = pd.DataFrame(matr ix, columns=headers)

In [0]:
term_matrix.head()

able  absolute  absolutely  access  accommodating  account  act  acted  \
0     0         0           0       0              0        0    0      0   
1     0         0           0       0              0        0    0      0   
2     0         0           0       0              0        0    0      0   
3     0         0           0       0              0        0    0      0   
4     0         0           0       0              0        0    0      0   

   actual  actually  ...   yelp  yelpers  yes  yesterday  yogurt  york  young  \
0       0         0  ...      0        0    0          0       0     0      0   
1       0         0  ...      0        0    0          0       0     0      0   
2       0         0  ...      0        0    0          0       0     0      0   
3       0         0  ...      0        0    1          0       0     0      0   
4       0         0  ...      0        0    0          0       0     0      0   

   yum  yummy  zero  
0    0      0     0  
1    0      1     0  
2    0      0     0  
3    0      0     0  
4    0      0     0  

[5 rows x 2000 columns]

In [0]:
train.loc[0].text

"If you're leaving Vegas, know that this is the very last time you will have to shell out an ungodly amount of money for pure crap. \\n\\nWe just wanted a nice refreshing soda with ice and a straw to sooth our yucky tummies. Little did I know that two small sodas would cost $6.25. \\n\\n$6.25!!!!!!!\\n\\nWhat a gigantic rip off. Complete usuary. Eff you, BK."

In [0]:
term_matrix.loc[0]

able             0
absolute         0
absolutely       0
access           0
accommodating    0
account          0
act              0
acted            0
actual           0
actually         0
add              0
added            0
addition         0
additional       0
address          0
admit            0
adult            0
advantage        0
advice           0
affordable       0
afternoon        0
age              0
ago              0
agree            0
agreed           0
ahead            0
air              0
airport          0
alcohol          0
allow            0
                ..
works            0
world            0
worry            0
worse            0
worst            0
worth            0
wouldn           0
wow              0
wrap             0
wrapped          0
write            0
writing          0
written          0
wrong            0
wtf              0
wynn             0
yeah             0
year             0
years            0
yellow           0
yelp             0
yelpers     

In [0]:
X_train = vect.fit_transform(train.text)
y_train = train.sentiment

In [0]:
X_train

<16000x2000 sparse matrix of type '<class 'numpy.int64'>'
	with 596026 stored elements in Compressed Sparse Row format>

In [0]:
# y_train

In [0]:
from sklearn.naive_bayes import MultinomialNB

In [0]:
nb = MultinomialNB()

In [0]:
nb.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
X_test = vect.transform(test.text)
y_test = test.sentiment

In [0]:
y_pred = nb.predict(X_test)

In [0]:
y_pred

array([1, 0, 1, ..., 1, 0, 0])

In [0]:
y_test

0       1
1       0
2       1
3       0
4       0
5       1
6       0
7       1
8       1
9       1
10      1
11      1
12      1
13      1
14      1
15      1
16      0
17      1
18      0
19      0
20      0
21      0
22      1
23      1
24      0
25      0
26      1
27      1
28      0
29      0
       ..
1970    0
1971    1
1972    1
1973    0
1974    1
1975    1
1976    1
1977    0
1978    0
1979    0
1980    1
1981    0
1982    1
1983    0
1984    0
1985    1
1986    0
1987    1
1988    1
1989    1
1990    0
1991    0
1992    1
1993    0
1994    0
1995    1
1996    0
1997    1
1998    0
1999    0
Name: sentiment, Length: 2000, dtype: int64

In [0]:
from sklearn import metrics

In [0]:
metrics.accuracy_score(y_test, y_pred)

0.8595

In [0]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.84      0.86      1000
           1       0.85      0.88      0.86      1000

   micro avg       0.86      0.86      0.86      2000
   macro avg       0.86      0.86      0.86      2000
weighted avg       0.86      0.86      0.86      2000



In [0]:
from sklearn.pipeline import make_pipeline

In [0]:
pipe = make_pipeline(vect, nb)

In [0]:
pipe.steps

[('countvectorizer',
  CountVectorizer(analyzer='word', binary=False, decode_error='strict',
          dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
          lowercase=True, max_df=0.8, max_features=2000, min_df=2,
          ngram_range=(1, 1), preprocessor=None, stop_words='english',
          strip_accents=None, token_pattern='(?u)\\b[^\\d\\W]\\w+\\b',
          tokenizer=None, vocabulary=None)),
 ('multinomialnb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))]

In [0]:
train.text

0        If you're leaving Vegas, know that this is the...
1        We were hungry and so quick bites of pizzas sa...
2        I have been calling around to various bakeries...
3        The first few visits here, we enjoyed it. The ...
4        Horrible service, menus never provided. Had to...
5        Nostalgia!\nFun for all ages!\nVintage pinball...
6        I was wandering around the Tempe Marketplace w...
7        Ambiance is wonderful..Service impeccable!\nWe...
8        I haven't been to any Motley Brews events exce...
9        My wife and I went a week earlier to celebrate...
10       We had reservations a few nights ago at Fiamma...
11       Bonus points for the selection of coffee beans...
12       I have been getting my hair cut @V's for close...
13       Had the Naked Burrito w/ half chicken and half...
14       Not clean. Literally Circus Circus and Motel 6...
15       Sooo what do you do when you hit a Royal Flush...
16       I have no clue why I continue to come to this .

In [0]:
train.sentiment

0        0
1        1
2        0
3        0
4        0
5        1
6        0
7        1
8        1
9        0
10       0
11       0
12       1
13       1
14       0
15       1
16       0
17       0
18       0
19       1
20       1
21       1
22       0
23       0
24       0
25       1
26       1
27       0
28       1
29       0
        ..
15970    1
15971    1
15972    1
15973    0
15974    0
15975    0
15976    1
15977    1
15978    1
15979    1
15980    0
15981    0
15982    1
15983    1
15984    1
15985    0
15986    1
15987    1
15988    1
15989    0
15990    1
15991    0
15992    1
15993    1
15994    0
15995    1
15996    0
15997    1
15998    1
15999    1
Name: sentiment, Length: 16000, dtype: int64

In [0]:
pipe.fit(train.text, train.sentiment)

Pipeline(memory=None,
     steps=[('countvectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.8, max_features=2000, min_df=2,
        ngram_range=(1, 1), preprocessor=None, stop_words='english',
        strip_accents=None, token_pattern='(?u)\\b[^\\d\\W]\\w+\\b',
        tokenizer=None, vocabulary=None)), ('multinomialnb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [0]:
test.head()

sentiment                                               text
0          1                            My favorite Thai place.
1          0  Long lines, unfriendly staff, worst place ever...
2          1  I was so surprised that Famous Uncle Al's was ...
3          0  I used to really like coming to Teriyaki Boy, ...
4          0  Okay so I go in to get my enchilada on. I aske...

In [0]:
pred = pipe.predict(test.text)

In [0]:
from textblob import TextBlob

In [0]:
def get_sentiment(text):
  pred = TextBlob(text).sentiment[0]
  if pred > 0:
    return 1
  else:
    return 0

In [0]:
test.text.apply(get_sentiment)

0       1
1       0
2       1
3       1
4       0
5       1
6       1
7       1
8       1
9       1
10      1
11      1
12      1
13      1
14      1
15      1
16      1
17      1
18      1
19      1
20      1
21      1
22      1
23      0
24      0
25      0
26      1
27      1
28      0
29      1
       ..
1970    1
1971    1
1972    1
1973    1
1974    1
1975    1
1976    1
1977    1
1978    1
1979    1
1980    1
1981    0
1982    1
1983    1
1984    1
1985    1
1986    0
1987    1
1988    1
1989    1
1990    0
1991    0
1992    1
1993    1
1994    1
1995    1
1996    1
1997    1
1998    1
1999    1
Name: text, Length: 2000, dtype: int64

In [0]:
print(metrics.classification_report(test.sentiment, test.text.apply(get_sentiment)))

              precision    recall  f1-score   support

           0       0.93      0.41      0.57      1000
           1       0.62      0.97      0.76      1000

   micro avg       0.69      0.69      0.69      2000
   macro avg       0.78      0.69      0.66      2000
weighted avg       0.78      0.69      0.66      2000

